project:
  type: website
  output-dir: docs

website:
  title: "RIMJHIM SAXENA"
  page-footer: "Copyright 2023, Rimjhim Saxena"
  google-analytics: "G-FP8EWB0450"
  sidebar: 
    tools: 
      - icon: twitter
        href: https://twitter.com/rimjhimster
      - icon: github
        href: https://github.com/rimjhimsaxena
      - icon: linkedin
        href: https://www.linkedin.com/in/rimjhimsaxena/
      - icon: filetype-pdf
        href: docs/images/CV_RimjhimSaxena.pdf


  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: docs/images/CV_RimjhimSaxena.pdf
        text: CV
      
  

format:
  html:
    theme: 
      light: zephyr
      dark: zephyr
    css: styles.css
    toc: true


editor: visual


