project:
  type: website
  output-dir: docs

website:
  title: "RIMJHIM SAXENA"
  favicon: images/favicon.png
  page-footer: "Copyright 2023, Rimjhim Saxena"
  google-analytics: "G-FP8EWB0450"
  cookie-consent: true
  search: 
    location: navbar
    type: overlay
 

  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: research.qmd
        text: Research
      - href: images/CV_RimjhimSaxena.pdf
        text: CV
      - href: posts.qmd
        text: Journal
        
    right:
      - icon: envelope
        href: mailto:rimjhim.saxena@colorado.edu
      - icon: twitter
        href: https://twitter.com/rimjhimster
      - icon: github
        href: https://github.com/rimjhimsaxena
      - icon: linkedin
        href: https://www.linkedin.com/in/rimjhimsaxena/
      - icon: filetype-pdf
        href: images/CV_RimjhimSaxena.pdf

  

format:
  html:
    theme: 
      light: zephyr
      dark: darkly
    css: styles.css
    toc: false
    tags:
    - Rimjhim Saxena
    - GitHub Pages
    - Economics 
    - PhD Candidate
    - PhD Economics
    - Environmental Economics
    - Labor Economics
    - Sustainable Development
    - Climate Change
    - Climate Change Economist
    - Academic
    - Economist
    - Google


editor: visual


