project:
  type: website
  output-dir: docs

website:
  title: "RIMJHIM SAXENA"
  favicon: images/favicon.png
  page-footer: "Copyright 2024, Rimjhim Saxena"
  google-analytics: "G-FP8EWB0450"
  cookie-consent: true

  search:
    location: navbar
    type: overlay

  navbar:
    pinned: true
    left:
      - href: index.qmd
        text: HOME
      - href: research.qmd
        text: RESEARCH
      - href: images/rimjhimsaxena_CV.pdf
        text: CV
      - href: teaching.qmd
        text: TEACHING
      - href: posts.qmd
        text: JOURNAL
    right:
      - icon: envelope
        href: mailto:rimjhim.saxena@unige.ch
      - icon: twitter
        href: https://twitter.com/rimjhimster
      - icon: github
        href: https://github.com/rimjhimsaxena
      - icon: linkedin
        href: https://www.linkedin.com/in/rimjhimsaxena/
      - icon: filetype-pdf
        href: images/rimjhimsaxena_CV.pdf

  open-graph: true
  twitter-card:
    creator: "@rimjhimster"
    card-style: summary_large_image

format:
  html:
    theme:
      light: [flatly, custom-light.scss]
      dark:  [darkly, custom-dark.scss]
    css: styles.css
    toc: false
    smooth-scroll: true
    tags:
      - Rimjhim Saxena
      - रिमझिम सक्सेना
      - Postdoctoral Researcher
      - Development Economics
      - Environmental Economics
      - Labor Economics
      - Agricultural Economics
      - Climate Adaptation
      - Water Economics
      - Energy Economics
      - Resource Economics
      - Applied Microeconomics
      - Indian Economy
      - South Asia
      - University of Geneva

editor: visual
