project:
  type: website
  output-dir: docs

website:
  title: "RIMJHIM SAXENA"
  page-footer: "Copyright 2023, Rimjhim Saxena"
  google-analytics: "G-FP8EWB0450"
  cookie-consent: true
  search: 
    location: navbar
    type: overlay
 

  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: research.qmd
        text: Research
      - href: docs/images/CV_RimjhimSaxena.pdf
        text: CV
        
    right:
      - icon: envelope
        href: mailto:rimjhim.saxena@colorado.edu
      - icon: twitter
        href: https://twitter.com/rimjhimster
      - icon: github
        href: https://github.com/rimjhimsaxena
      - icon: linkedin
        href: https://www.linkedin.com/in/rimjhimsaxena/
      - icon: filetype-pdf
        href: docs/images/CV_RimjhimSaxena.pdf

  

format:
  html:
    theme: 
      light: zephyr
      dark: darkly
    css: styles.css
    toc: false


editor: visual


